### ISSUE TITLE
make compilable with derive-storable-0.3.1

### ISSUE THREAD

**Issue by amigalemming** [prsteele/glpk-headers-haskell#16]
There is a new version of `derive-storable` available and `glpk-headers` fails using it:

~~~~
src/Math/Programming/Glpk/Header.hsc:1503:7: error:
    • No instance for (GStorable CInt)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (GStorable GlpkFactorizationType)
     |
1503 |     , GStorable
     |       ^^^^^^^^^
~~~~

**Comment by prsteele** [comment]
I've made the changes to allow this to compile with the new `derive-storable` library, but this is happening over at https://github.com/prsteele/math-programming . I'll be archiving this repository shortly, and will release a version `0.5.0` of this library to Hackage (again, from the new repository.)
