### ISSUE TITLE
please release new version

### ISSUE THREAD

**Issue by amigalemming** [prsteele/glpk-headers-haskell#17]
There seem to be some problems resolved in HEAD. Please release a new version to Hackage.

**Comment by prsteele** [comment]
Version `0.5.0` will be released shortly. Note that development is continuing at https://github.com/prsteele/math-programming instead of this repository.

**Comment by prsteele** [comment]
@amigalemming https://hackage.haskell.org/package/glpk-headers-0.5.0 now exists.
